INSERT INTO VALENTINA.BOOK VALUES (4, 'CEVA', sysdate, 56.98, 'AAA25AA', 'description', 'cover', 134, 'romana', 4.5);
INSERT INTO VALENTINA.AUTHOR VALUES (1, 'Autor1');
INSERT INTO VALENTINA.BOOK_AUTHOR VALUES (4, 1);
INSERT INTO VALENTINA.CATEGORY VALUES (1, 'cATEGORY1');
INSERT INTO VALENTINA.BOOK_CATEGORY VALUES (4, 'SCIENCE');
