INSERT INTO BOOK VALUES(books_app_seq.nextVal, 'Outlander', '01-JUN-1991', 10.36, '978-0440212560',
                      'Outlander (published in the United Kingdom as Cross Stitch) is the first in a series of eight historical multi-genre novels by Diana Gabaldon. Published in 1991, it focuses on 20th century nurse Claire Randall, who time travels to 18th century Scotland and finds adventure and romance with the dashing James Fraser. A mix of several genres, the Outlander series features elements of historical fiction, romance, adventure and science fiction/fantasy. Outlander won the Romance Writers of America''s RITA Award for Best Romance of 1991. A television adaptation of the Outlander series premiered on Starz in the US on August 9, 2014',
                       'book1.jpeg', 796, 'English', 5);
INSERT INTO BOOK VALUES(books_app_seq.nextVal, 'Harry Potter and the Philosopher''s Stone', '26-JUN-1997', 8.45, '0-7475-3269-9',
                      'Harry Potter and the Philosopher''s Stone is the first novel in the Harry Potter series and J. K. Rowling''s debut novel. The plot follows Harry Potter, a young wizard who discovers his magical heritage as he makes close friends and a few enemies in his first year at the Hogwarts School of Witchcraft and Wizardry. With the help of his friends, Harry faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry''s parents, but failed to kill Harry when he was just a year old. The book, which was Rowling''s debut novel, was published on 26 June 1997 by Bloomsbury in London. In 1998, Scholastic Corporation published an edition for the United States market under the title Harry Potter and the Sorcerer''s Stone. The novel won most of the British book awards that were judged by children and other awards in the US. The book reached the top of the New York Times list of best-selling fiction in August 1999 and stayed near the top of that list for much of 1999 and 2000. It has been translated into several other languages and has been made into a feature-length film of the same name. Most reviews were very favourable, commenting on Rowling''s imagination, humour, simple, direct style and clever plot construction, although a few complained that the final chapters seemed rushed. The writing has been compared to that of Jane Austen, one of Rowling''s favourite authors, or Roald Dahl, whose works dominated children''s stories before the appearance of Harry Potter, and of the Ancient Greek story-teller Homer. While some commentators thought the book looked backwards to Victorian and Edwardian boarding school stories, others thought it placed the genre firmly in the modern world by featuring contemporary ethical and social issues.',
                       'Harry_Potter_1.jpeg', 309, 'English', 0);
INSERT INTO BOOK VALUES(books_app_seq.nextVal, 'Harry Potter and the Chamber of Secrets', '02-JUl-1998', 8.78, '0-7475-3849-2',
                      'Harry Potter and the Chamber of Secrets is the second novel in the Harry Potter series, written by J. K. Rowling. The plot follows Harry''s second year at Hogwarts School of Witchcraft and Wizardry, during which a series of messages on the walls of the school''s corridors warn that the "Chamber of Secrets" has been opened and that the "heir of Slytherin" would kill all pupils who do not come from all-magical families. These threats are followed by attacks which leave residents of the school "petrified" (frozen like stone). Throughout the year, Harry and his friends Ron Weasley and Hermione Granger investigate the attacks. The book was published in the United Kingdom on 2 July 1998 by Bloomsbury and in the United States on 2 June 1999 by Scholastic Inc. Although Rowling found it difficult to finish the book, it won high praise and awards from critics, young readers and the book industry, although some critics thought the story was perhaps too frightening for younger children. Much like with other novels in the series, Harry Potter and the Chamber of Secrets triggered religious debates; some religious authorities have condemned its use of magical themes, while others have praised its emphasis on self-sacrifice and on the way in which a person''s character is the result of the person''s choices. Several commentators have noted that personal identity is a strong theme in the book, and that it addresses issues of racism through the treatment of non-magical, non-human and non-living characters. Some commentators regard the diary as a warning against uncritical acceptance of information from sources whose motives and reliability cannot be checked. Institutional authority is portrayed as self-serving and incompetent. The book is also known to have some connections to the sixth novel of the series, Harry Potter and the Half-Blood Prince. The film adaptation of the novel, released in 2002, became (at that time) the seventh highest grossing film ever and received generally favourable reviews. Video games loosely based on Harry Potter and the Chamber of Secrets were also released for several platforms, and most obtained favourable reviews.',
                       'Harry_Potter_2.jpeg', 341, 'English', 0);
INSERT INTO BOOK VALUES(books_app_seq.nextVal, 'Harry Potter and the Prisoner of Azkaban', '08-SEP-1999', 9.05, '0-7475-4215-5',
                      'Harry Potter and the Prisoner of Azkaban is the third novel in the Harry Potter series, written by J. K. Rowling. The book follows Harry Potter, a young wizard, in his third year at Hogwarts School of Witchcraft and Wizardry. Along with friends Ron Weasley and Hermione Granger, Harry investigates Sirius Black, an escaped prisoner from Azkaban whom they believe is one of Lord Voldemort''s old allies. The book was published in the United Kingdom on 8 July 1999 by Bloomsbury and in the United States on 8 September 1999 by Scholastic Inc.[2][3][4][5] Rowling found the book easy to write, finishing it just a year after she had begun writing it. The book sold 68,000 copies in just three days after its release in the United Kingdom, and since has sold over three million in the country.[6] The book won the 1999 Whitbread Children''s Book Award, the Bram Stoker Award, the 2000 Locus Award for Best Fantasy Novel, and was short-listed for other awards, including the Hugo. The film adaptation of the novel was released in 2004, grossing more than $796 million and earned notable critical acclaim. Video games loosely based on Harry Potter and the Prisoner of Azkaban were also released for several platforms, and most obtained favourable reviews.',
                       'Harry_Potter_3.jpeg', 435, 'English', 0);
INSERT INTO BOOK VALUES(books_app_seq.nextVal, 'Harry Potter and the Goblet of Fire', '08-JUL-2000', 9.62, '0-7475-4624-1',
                      'Harry Potter and the Goblet of Fire is the fourth novel in the Harry Potter series, written by British author J. K. Rowling. It follows Harry Potter, a wizard in his fourth year at Hogwarts School of Witchcraft and Wizardry and the mystery surrounding the entry of Harry''s name into the Triwizard Tournament, in which he is forced to compete. The book was published in the United Kingdom by Bloomsbury and in the United States by Scholastic, in both countries the release date was 8 July 2000, the first time a book in the series was published in both countries at the same time. The novel won a Hugo Award, the only Harry Potter novel to do so, in 2001. The book was made into a film, which was released worldwide on 18 November 2005, and a video game by Electronic Arts. Throughout the three previous novels in the Harry Potter series, the main character, Harry Potter, has struggled with the difficulties of growing up, and the added challenge of being a famed wizard: when Harry was a baby, Lord Voldemort, the most powerful Dark wizard in history, killed Harry''s parents but mysteriously vanished after unsuccessfully trying to kill Harry, which left a lightning-shaped scar on Harry''s forehead. This results in Harry''s immediate fame and his being placed in the care of his muggle, or non-magical aunt and uncle, Aunt Petunia Dursley and Uncle Vernon Dursley, who have a son named Dudley Dursley. Harry learns that he is a wizard when he is 11 years old, just before he enrolls in Hogwarts School of Witchcraft and Wizardry. He befriends Ron Weasley and Hermione Granger, and is confronted by Lord Voldemort who is trying to regain power. In Harry''s first year he has to protect the Philosopher''s Stone from Voldemort and one of his faithful followers at Hogwarts. After returning to the school after summer break, students at Hogwarts are attacked by the legendary monster of the "Chamber of Secrets" after the chamber is opened. Harry ends the attacks by killing a Basilisk and defeating another attempt by Lord Voldemort to return to full strength. The following year, Harry hears that he has been targeted by escaped mass murderer Sirius Black. Despite stringent security measures at Hogwarts, Harry is confronted by Black at the end of his third year of schooling, and Harry learns that Black was framed and is actually Harry''s godfather. He also learned that it was his father''s old school friend Peter Pettigrew who actually betrayed his parents.',
                       'Harry_Potter_4.jpeg', 734, 'English', 0);
INSERT INTO BOOK VALUES(books_app_seq.nextVal, 'Harry Potter and the Order of the Phoenix', '21-JUN-2003', 7.21, '0-7475-5100-6',
                      'During another summer with his Aunt Petunia and Uncle Vernon, Harry Potter and Dudley are attacked by dementors. After using magic to save Dudley and himself, Harry is expelled from Hogwarts, but the decision is later rescinded. Harry is whisked off by a group of wizards to Number 12, Grimmauld Place, the home of his godfather, Sirius Black. The house also serves as the headquarters of the Order of the Phoenix, of which Mr. and Mrs. Weasley, Remus Lupin, Mad-Eye Moody, and Sirius are members. Ron Weasley and Hermione Granger explain that the Order of the Phoenix is a secret organisation led by Hogwarts headmaster Albus Dumbledore, dedicated to fighting Lord Voldemort and his followers, the Death Eaters. From the members of the Order, Harry and the others learn that Voldemort is seeking an object that he did not have prior to his first defeat, and assume this object to be a weapon of some sort. Harry learns that the Ministry of Magic, led by Cornelius Fudge, is refusing to acknowledge Voldemort''s return because of the trouble that doing so would cause, and has been running a smear campaign against him and Dumbledore.',
                       'Harry_Potter_5.jpeg', 870, 'English', 0);
INSERT INTO BOOK VALUES(books_app_seq.nextVal, 'The Maze Runner', '25-FEB-2009', 11.56, '978-0-385-73794-4',
                      'A boy wakes up in a box with no memory of his past, other than his name, Thomas. When the elevator doors open, he is pulled into a glade by a group of teenage boys who also have no memories besides their name. Thomas gradually discovers that the Glade is run by two boys: Alby, the leader, and Newt, the second-in-charge, who both maintain order by enforcing strict rules. Outside the Glade is the Maze, a labyrinth of high walls covered in ivy that houses strange, lethal creatures known as Grievers. Grievers are described as monsters of metal and flesh, and are depicted in the film directed by Wes Ball as robotic spiders designed by the organization WICKED. The Gladers are trying to stay alive as well as "solve" the Maze by running through it as fast as they can while tracking movements of the walls and trying to find an exit to escape.Every month the box is sent up with a new person called a "greenie" and every two weeks supplies are sent. After Thomas''s arrival, a girl is delivered through the elevator into the Glade, and subsequently lapses into a coma. When Thomas comes to visit her, he recognizes her, but can''t remember her name until he hears her voice telepathically in his head. Her arrival triggers everything in the Glade to change: the sun disappears, the deliveries of supplies stop coming, and the doors of the Maze stay open at night, which allows the Grievers to enter the Glade and hunt the children. She also arrives with a note from WICKED, the creators of the glade that says: She is the last one, ever, implying that there were to be no more children sent into the Glade.',
                       'The_Maze_Runner.jpeg', 375, 'English', 0);
INSERT INTO BOOK VALUES(books_app_seq.nextVal, 'The Scorch Trials', '18-SEP-2010', 10.36, '978-0-385-73875-0',
                      'The book starts with Thomas and the other teenagers known as "the Gladers," who had escaped from an experiment known as The Maze in the previous book, sleeping in the dormitory they were brought to by a group of rescuers. Thomas is woken by a telepathic communication with Teresa, the only female Glader, who is afraid. As he wakes up, he finds that the facility is being attacked by Cranks, aggressive zombie-like people that have been affected by a plague known as "the Flare." He and other Gladers escape into the facility''s common area and discover that their rescuers are dead. They also find that Teresa is missing from her room, and in her place is a boy named Aris Jones. Aris explains that he escaped from a similar Maze experiment, dubbed "Group B," in which he was the only male. The boys discover tattoos on their necks assigning them roles. Aris is "The Partner," Newt is "The Glue," and Minho is "The Leader," while Thomas'' tattoo reads "To Be Killed by Group B." The Gladers re-enter the common area and find the bodies of their rescuers have disappeared. They find one of the scientists from WICKED, the organization that created the experiment, who explains that WICKED has been studying them to try to find a cure for the Flare. He tells them they have been infected with the Flare and must in two weeks get through the Scorch, a burned out section of the land, to find a safe haven and get the cure.',
                       'The_Scorch_Trials.jpeg', 368, 'English', 0);
INSERT INTO BOOK VALUES(books_app_seq.nextVal, 'The Death Cure', '17-AUG-2011', 17.85, '978-0-385-73877-4',
                      'The protagonist, Thomas, is held in solitary confinement, but is eventually released by Assistant Director Janson, who tells the Gladers and Group B that there is a cure for the Flare (a deadly disease). Many of those present were immune to the Flare while some, including Newt, were not, and escaping would serve no purpose, for people in the outside world despise the Immunes. The Gladers are offered the chance to restore their memories and remove the controllers in their heads. Without the devices, Thomas, Teresa, and Aris will no longer be able to communicate telepathically. Thomas, Minho, and Newt were the only ones to choose not to undergo the procedure, but Janson later attempts to force them into the process, because he feels that they will be no help to finding the cure if they don''t get their memories back. All three of them escape before having chips removed, with the help of Brenda and Jorge, who are revealed to be working for WICKED, and were sent to the Scorch as an assignment. Thomas feels betrayed, but Brenda convinces him that she had no choice and that most of her behavior was not a deception, and Thomas forgives. Soon afterward, the Gladers discover that everyone who had undergone the restoration procedure had abandoned them, and Newt begins to succumb to the Flare, suffering sharp mood swings. Newt gives Thomas a note and tells him to open it "when the time is right."',
                       'The_Death_Cure.jpeg', 325, 'English', 0);
INSERT INTO BOOK VALUES(books_app_seq.nextVal, 'Design Patterns', '01-JAN-1994', 25.75, '0-201-63361-2',
                      'Design Patterns: Elements of Reusable Object-Oriented Software is a software engineering book describing recurring solutions to common problems in software design. The book''s authors are Erich Gamma, Richard Helm, Ralph Johnson and John Vlissides with a foreword by Grady Booch. The book is divided into two parts, with the first two chapters exploring the capabilities and pitfalls of object-oriented programming, and the remaining chapters describing 23 classic software design patterns. The book includes examples in C++ and Smalltalk. It has been highly influential to the field of software engineering and is regarded as an important source for object-oriented design theory and practice. More than 500,000 copies have been sold in English and in 13 other languages. The authors are often referred to as the Gang of Four (GoF).',
                       'book2.jpeg', 395, 'English', 0);
INSERT INTO BOOK VALUES(books_app_seq.nextVal, 'The Hunger Games', '14-SEP-2008', 21.34, '978-0-439-02352-8',
                      'The Hunger Games takes place in a nation known as Panem, established in North America after the destruction of the continent''s civilization by an unknown apocalyptic event. The nation consists of the wealthy Capitol and twelve surrounding, poorer districts united under the Capitol''s control. District 12, where the book begins, is located in the coal-rich region that was formerly known as Appalachia. As punishment for a past rebellion against the Capitol, in which a 13th district was destroyed, one boy and one girl between the ages of 12 and 18 from each district are selected by an annual lottery to participate in the Hunger Games, an event in which the participants, the "tributes", must fight to the death in an outdoor arena controlled by the Capitol, until only one individual remains. The story is narrated by 16-year-old Katniss Everdeen, a girl from District 12 who volunteers for the 74th annual Hunger Games in place of her younger sister, Primrose. The male tribute chosen from District 12 is Peeta Mellark, a former schoolmate of Katniss who once gave her bread from his family''s bakery when her family was starving.',
                       'The_Hunger_Games.jpeg', 374, 'English', 0);

INSERT INTO BOOK VALUES(books_app_seq.nextVal, 'Catching Fire', '1-SEP-2009', 24.32, '978-0-545-22724-7',
                        'After winning the 74th Hunger Games in the previous novel, Katniss Everdeen and Peeta Mellark return home to District 12, the poorest sector in the country of Panem. But on the day that Katniss and Peeta are to start a "Victory Tour" of the country, President Snow visits unexpectedly and tells Katniss that he is angry with her for breaking the rules at the end of the last Hunger Games, which permitted both Peeta and Katniss to win. Snow tells Katniss that when she defied the Capitol, she inspired rebellion in the districts.',
                        'Catching_Fire.jpeg', 391, 'English', 0);

INSERT INTO BOOK VALUES(books_app_seq.nextVal, 'Mockingjay', '24-AUG-2010', 28.3, '978-0-439-02351-1',
                      'Katniss, her sister Prim, and her friends Finnick and Gale all reluctantly adjust to a highly structured life in the underground District 13, which has been spearheading the rebellion in Panem. Feeling manipulated, Katniss eventually agrees to act as "the Mockingjay"a poster child for the rebellion, but only on the condition that District 13''s President Alma Coin vows to grant immunity to all of the past Hunger Games tributes, including Katniss''s friend Peeta Mellark and Finnick''s lover Annie Cresta, and to reserve for Katniss the right to personally kill Panem''s President Snow once he is captured.',
                      'Mockingjay.jpeg', 390, 'English', 4);

INSERT INTO BOOK VALUES(books_app_seq.nextVal, 'Amintiri din copilarie', '1-JAN-1982', 60, '800-0-343-34433-1',
                      'Relatarea lui Creanga incepe cu un monolog extensiv si cu o descriere nostalgica a locului nasterii sale, cu o scurta prezentare a istoriei Humulestiului si a statutului social al familiei. Primul capitol se concentreaza pe mai multe personaje legate direct de primii ani de scoala ai lui Nica: Vasile a Ilioaei, tanarul învatator si cleric ortodox, care il înscrie in clasa nou infiintata; superiorul lui Vasile, preotul paroh; Smarandita, fata inteligenta, dar neastamparata, a preotului; tatal lui Creanga, Stefan, si mama Smaranda.',
                      'Amintiri_din_copilarie.jpeg', 200, 'Romana', 0);